/* Automatically generated by './build/bin/build-entry.js' */
import { inject } from 'vue'
// import Pagination from '../packages/pagination/button.spec.js';
// import Dialog from '../packages/dialog/button.spec.js';
// import Autocomplete from '../packages/autocomplete/button.spec.js';
// import Dropdown from '../packages/dropdown/button.spec.js';
// import DropdownMenu from '../packages/dropdown-menu/button.spec.js';
// import DropdownItem from '../packages/dropdown-item/button.spec.js';
// import Menu from '../packages/menu/button.spec.js';
// import Submenu from '../packages/submenu/button.spec.js';
// import MenuItem from '../packages/menu-item/button.spec.js';
// import MenuItemGroup from '../packages/menu-item-group/button.spec.js';
import Input from '../packages/input/index.js';
import InputNumber from '../packages/input-number/index.js';
import Radio from '../packages/radio/index.js';
import RadioGroup from '../packages/radio-group/index.js';
import RadioButton from '../packages/radio-button/index.js';
// import Checkbox from '../packages/checkbox/button.spec.js';
// import CheckboxButton from '../packages/checkbox-button/button.spec.js';
// import CheckboxGroup from '../packages/checkbox-group/button.spec.js';
// import Switch from '../packages/switch/button.spec.js';
// import Select from '../packages/select/button.spec.js';
// import Option from '../packages/option/button.spec.js';
// import OptionGroup from '../packages/option-group/button.spec.js';
import Button from '../packages/button/index.js'
// import ButtonGroup from '../packages/button-group/button.spec.js';
// import Table from '../packages/table/button.spec.js';
// import TableColumn from '../packages/table-column/button.spec.js';
// import DatePicker from '../packages/date-picker/button.spec.js';
// import TimeSelect from '../packages/time-select/button.spec.js';
// import TimePicker from '../packages/time-picker/button.spec.js';
// import Popover from '../packages/popover/button.spec.js';
// import Tooltip from '../packages/tooltip/button.spec.js';
// import MessageBox from '../packages/message-box/button.spec.js';
// import Breadcrumb from '../packages/breadcrumb/button.spec.js';
// import BreadcrumbItem from '../packages/breadcrumb-item/button.spec.js';
import Form from '../packages/form/index.js';
import FormItem from '../packages/form-item/index.js';
// import Tabs from '../packages/tabs/button.spec.js';
// import TabPane from '../packages/tab-pane/button.spec.js';
import Tag from '../packages/tag/index.js';
// import Tree from '../packages/tree/button.spec.js';
// import Alert from '../packages/alert/button.spec.js';
// import Notification from '../packages/notification/button.spec.js';
// import Slider from '../packages/slider/button.spec.js';
// import Loading from '../packages/loading/button.spec.js';
// import Icon from '../packages/icon/button.spec.js';
import Row from '../packages/row/index.js'
import Col from '../packages/col/index.js'
// import Upload from '../packages/upload/button.spec.js';
// import Progress from '../packages/progress/button.spec.js';
// import Spinner from '../packages/spinner/button.spec.js';
// import Message from '../packages/message/button.spec.js';
// import Badge from '../packages/badge/button.spec.js';
// import Card from '../packages/card/button.spec.js';
// import Rate from '../packages/rate/button.spec.js';
// import Steps from '../packages/steps/button.spec.js';
// import Step from '../packages/step/button.spec.js';
// import Carousel from '../packages/carousel/button.spec.js';
import Scrollbar from '../packages/scrollbar/index.js';
// import CarouselItem from '../packages/carousel-item/button.spec.js';
// import Collapse from '../packages/collapse/button.spec.js';
// import CollapseItem from '../packages/collapse-item/button.spec.js';
// import Cascader from '../packages/cascader/button.spec.js';
// import ColorPicker from '../packages/color-picker/button.spec.js';
// import Transfer from '../packages/transfer/button.spec.js';
import Container from '../packages/container/index.js';
import Header from '../packages/header/index.js';
import Aside from '../packages/aside/index.js';
import Main from '../packages/main/index.js';
import Footer from '../packages/footer/index.js';
// import Timeline from '../packages/timeline/button.spec.js';
// import TimelineItem from '../packages/timeline-item/button.spec.js';
import Link from '../packages/link/index.js';
// import Divider from '../packages/divider/button.spec.js';
// import Image from '../packages/image/button.spec.js';
// import Calendar from '../packages/calendar/button.spec.js';
// import Backtop from '../packages/backtop/button.spec.js';
// import InfiniteScroll from '../packages/infinite-scroll/button.spec.js';
// import PageHeader from '../packages/page-header/button.spec.js';
// import CascaderPanel from '../packages/cascader-panel/button.spec.js';
// import Avatar from '../packages/avatar/button.spec.js';
// import Drawer from '../packages/drawer/button.spec.js';
// import locale from 'element-ui/src/locale';
// import CollapseTransition from 'element-ui/src/transitions/collapse-transition';

const components = [
  // Pagination,
  // Dialog,
  // Autocomplete,
  // Dropdown,
  // DropdownMenu,
  // DropdownItem,
  // Menu,
  // Submenu,
  // MenuItem,
  // MenuItemGroup,
  Input,
  InputNumber,
  Radio,
  RadioGroup,
  RadioButton,
  // Checkbox,
  // CheckboxButton,
  // CheckboxGroup,
  // Switch,
  // Select,
  // Option,
  // OptionGroup,
  Button,
  // ButtonGroup,
  // Table,
  // TableColumn,
  // DatePicker,
  // TimeSelect,
  // TimePicker,
  // Popover,
  // Tooltip,
  // Breadcrumb,
  // BreadcrumbItem,
  Form,
  FormItem,
  // Tabs,
  // TabPane,
  Tag,
  // Tree,
  // Alert,
  // Slider,
  // Icon,
  Row,
  Col,
  // Upload,
  // Progress,
  // Spinner,
  // Badge,
  // Card,
  // Rate,
  // Steps,
  // Step,
  // Carousel,
  Scrollbar,
  // CarouselItem,
  // Collapse,
  // CollapseItem,
  // Cascader,
  // ColorPicker,
  // Transfer,
  Container,
  Header,
  Aside,
  Main,
  Footer,
  // Timeline,
  // TimelineItem,
  Link,
  // Divider,
  // Image,
  // Calendar,
  // Backtop,
  // PageHeader,
  // CascaderPanel,
  // Avatar,
  // Drawer,
  // CollapseTransition
]

// 常量
const ELEMENTSymbol = Symbol()

const install = function (app, opts = {}) {
  // locale.use(opts.locale);
  // locale.i18n(opts.i18n);

  // register components
  components.forEach(component => {
    // debugger
    app.component(component.name, component)
  })

  // Vue.use(InfiniteScroll);
  // Vue.use(Loading.directive);

  /***
   *   Vue.prototype.$ELEMENT = {
        size: opts.size || '',
        zIndex: opts.zIndex || 2000
       };
   */
  app.provide(ELEMENTSymbol, {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  })


  // Vue.prototype.$loading = Loading.service;
  // Vue.prototype.$msgbox = MessageBox;
  // Vue.prototype.$alert = MessageBox.alert;
  // Vue.prototype.$confirm = MessageBox.confirm;
  // Vue.prototype.$prompt = MessageBox.prompt;
  // Vue.prototype.$notify = Notification;
  // Vue.prototype.$message = Message;

}

export function useELEMENT () {
  return inject(ELEMENTSymbol, undefined)
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  version: '2.11.1',
  // locale: locale.use,
  // i18n: locale.i18n,
  install,
  // CollapseTransition,
  // Loading,
  // Pagination,
  // Dialog,
  // Autocomplete,
  // Dropdown,
  // DropdownMenu,
  // DropdownItem,
  // Menu,
  // Submenu,
  // MenuItem,
  // MenuItemGroup,
  // Input,
  // InputNumber,
  // Radio,
  // RadioGroup,
  // RadioButton,
  // Checkbox,
  // CheckboxButton,
  // CheckboxGroup,
  // Switch,
  // Select,
  // Option,
  // OptionGroup,
  // Button,
  // ButtonGroup,
  // Table,
  // TableColumn,
  // DatePicker,
  // TimeSelect,
  // TimePicker,
  // Popover,
  // Tooltip,
  // MessageBox,
  // Breadcrumb,
  // BreadcrumbItem,
  // Form,
  // FormItem,
  // Tabs,
  // TabPane,
  // Tag,
  // Tree,
  // Alert,
  // Notification,
  // Slider,
  // Icon,
  // Row,
  // Col,
  // Upload,
  // Progress,
  // Spinner,
  // Message,
  // Badge,
  // Card,
  // Rate,
  // Steps,
  // Step,
  // Carousel,
  // Scrollbar,
  // CarouselItem,
  // Collapse,
  // CollapseItem,
  // Cascader,
  // ColorPicker,
  // Transfer,
  // Container,
  // Header,
  // Aside,
  // Main,
  // Footer,
  // Timeline,
  // TimelineItem,
  // Link,
  // Divider,
  // Image,
  // Calendar,
  // Backtop,
  // InfiniteScroll,
  // PageHeader,
  // CascaderPanel,
  // Avatar,
  // Drawer
}
